### ISSUE TITLE
Node app crashes on start

### ISSUE THREAD

**Issue by mihaiborbea** [googlecodelabs/cloud-cardboard-viewer#26]
In the 4th step of this codelab, when you type `npm start` the app crashes with this error:

> /home/borbeamihai/cloud-cardboard-viewer/node_modules/@google-cloud/debug-agent/src/agent/state.js:24
> var ScopeType = require('vm').runInDebugContext('ScopeType');
> TypeError: require(...).runInDebugContext is not a function
>     at Object.<anonymous> (/home/borbeamihai/cloud-cardboard-viewer/node_modules/@google-cloud/debug-agent/src/agent/state.js:24:31)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/home/borbeamihai/cloud-cardboard-viewer/node_modules/@google-cloud/debug-agent/src/agent/v8debugapi.js:24:27)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by pattch** [comment]
+1, I'm also seeing this issue after a clean clone of this repo with the same stack trace.

**Comment by ahellingil** [comment]
Me too. It could be the node.js version? I have v11.13.0 and before the error, I obtain a warning: "You're using Node.js v11.13.0 but the Google Cloud Functions runtime is only available in Node.js 6 and Node.js 8. Therefore, results from running emulated functions may not match production behavior."

**Comment by seleniusmoell** [comment]
I'm getting the same. I have Node.js v12.13.0.
